// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecorridoHistoricoApi.Data;

#nullable disable

namespace RecorridoHistoricoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HorarioTipo", b =>
                {
                    b.Property<int>("HorariosId")
                        .HasColumnType("int")
                        .HasColumnName("horarios_id");

                    b.Property<int>("TiposRecorridoId")
                        .HasColumnType("int")
                        .HasColumnName("tipos_recorrido_id");

                    b.HasKey("HorariosId", "TiposRecorridoId")
                        .HasName("pk_horario_tipo");

                    b.HasIndex("TiposRecorridoId")
                        .HasDatabaseName("ix_horario_tipo_tipos_recorrido_id");

                    b.ToTable("horario_tipo", (string)null);
                });

            modelBuilder.Entity("RecorridoHistoricoApi.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cedula");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_empleados");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("RecorridoHistoricoApi.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_estados");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("RecorridoHistoricoApi.Models.FechaManual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("comentario");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("EsRecurrente")
                        .HasColumnType("bit")
                        .HasColumnName("es_recurrente");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("Date")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.HasKey("Id")
                        .HasName("pk_fechas_manuales");

                    b.ToTable("FechasManuales");
                });

            modelBuilder.Entity("RecorridoHistoricoApi.Models.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Dia")
                        .HasColumnType("int")
                        .HasColumnName("dia");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hora");

                    b.Property<int>("TandaId")
                        .HasColumnType("int")
                        .HasColumnName("tanda_id");

                    b.HasKey("Id")
                        .HasName("pk_horarios");

                    b.HasIndex("TandaId")
                        .HasDatabaseName("ix_horarios_tanda_id");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("RecorridoHistoricoApi.Models.RecorridoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<int>("AsignadoAId")
                        .HasColumnType("int")
                        .HasColumnName("asignado_a_id");

                    b.Property<int>("CantidadVisitantes")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_visitantes");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cedula");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("estado_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaCulminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_culminacion");

                    b.Property<DateTime>("FechaVisita")
                        .HasColumnType("Date")
                        .HasColumnName("fecha_visita");

                    b.Property<int>("HorarioId")
                        .HasColumnType("int")
                        .HasColumnName("horario_id");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("idioma");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("institucion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefono");

                    b.Property<int>("TipoRecorridoId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_recorrido_id");

                    b.HasKey("Id")
                        .HasName("pk_recorridos_historico");

                    b.HasIndex("AsignadoAId")
                        .HasDatabaseName("ix_recorridos_historico_asignado_a_id");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("ix_recorridos_historico_estado_id");

                    b.HasIndex("HorarioId")
                        .HasDatabaseName("ix_recorridos_historico_horario_id");

                    b.HasIndex("TipoRecorridoId")
                        .HasDatabaseName("ix_recorridos_historico_tipo_recorrido_id");

                    b.ToTable("RecorridosHistorico");
                });

            modelBuilder.Entity("RecorridoHistoricoApi.Models.Tanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("pk_tandas");

                    b.ToTable("Tandas");
                });

            modelBuilder.Entity("RecorridoHistoricoApi.Models.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CantidadMaxima")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_maxima");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsFlexible")
                        .HasColumnType("bit")
                        .HasColumnName("es_flexible");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tipos");

                    b.ToTable("Tipos");
                });

            modelBuilder.Entity("HorarioTipo", b =>
                {
                    b.HasOne("RecorridoHistoricoApi.Models.Horario", null)
                        .WithMany()
                        .HasForeignKey("HorariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horario_tipo_horarios_horarios_id");

                    b.HasOne("RecorridoHistoricoApi.Models.Tipo", null)
                        .WithMany()
                        .HasForeignKey("TiposRecorridoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horario_tipo_tipos_tipos_recorrido_id");
                });

            modelBuilder.Entity("RecorridoHistoricoApi.Models.Horario", b =>
                {
                    b.HasOne("RecorridoHistoricoApi.Models.Tanda", "Tanda")
                        .WithMany()
                        .HasForeignKey("TandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horarios_tandas_tanda_id");

                    b.Navigation("Tanda");
                });

            modelBuilder.Entity("RecorridoHistoricoApi.Models.RecorridoHistorico", b =>
                {
                    b.HasOne("RecorridoHistoricoApi.Models.Empleado", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recorridos_historico_empleados_asignado_a_id");

                    b.HasOne("RecorridoHistoricoApi.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recorridos_historico_estados_estado_id");

                    b.HasOne("RecorridoHistoricoApi.Models.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recorridos_historico_horarios_horario_id");

                    b.HasOne("RecorridoHistoricoApi.Models.Tipo", "TipoRecorrido")
                        .WithMany()
                        .HasForeignKey("TipoRecorridoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recorridos_historico_tipos_tipo_recorrido_id");

                    b.Navigation("AsignadoA");

                    b.Navigation("Estado");

                    b.Navigation("Horario");

                    b.Navigation("TipoRecorrido");
                });
#pragma warning restore 612, 618
        }
    }
}
