<html>
  <head>
    <style>

    </style>
  </head>
  <body>
    <p>Sr. <strong> $name$</strong> </p>
    
    <p>
      Gracias por solicitar nuestro servicio de <strong>$service$</strong>
    </p>

    <p>
      Le informamos que hemos recibido su solicitud No.<strong> $requestNumber$ </strong> se encuentra pendiente en nuestro sistema. Este servicio es totalmente
      gratis y se le dará respuesta de la disponibilidad de la fecha solicitada en no más de <strong>$daysNumber$</strong> días laborables, para garantizar su experiencia y acceso a la Casa de Gobierno. 
    </p>

    <p>
      En caso de requerir información adicional, puede contactarnos llamando al <strong> $phoneNumber$  ext. $ext$</strong>
    </p>

    <p>
      <strong>Nota:</strong>  Este correo electrónico se genera de manera automática por el sistema,  le solicitamos
      no responder a este mensaje.
    </p>

    <p>
      <strong>Ministerio Administrativo de la Presidencia</strong>
    </p>

    <a href="http://172.20.3.14/dashnew#!/home?department=$deptid$">Click aquí para ver en la aplicación</a>
  </body>
</html>